# to use orbs, must use version >= 2.1
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.4.0
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          start: yarn start
          wait-on: 'http://127.0.0.1:4201'